#!/usr/bin/env sh

while true; do         
       date '+%a %d %b %Y | %T' > /tmp/CurTime.tmp         
       sleep 1s 
done &

while true; do
        CPU=$(top -bn1 | grep load | awk '{printf "%.2f\n", $(NF-2)}')
        MEM=$(free -h | awk '/^Mem:/ {print $3}')
        LOCALTIME=$(< /tmp/CurTime.tmp)
        BHT=$(cat /sys/class/power_supply/BAT0/capacity)
        NET=$(nmcli dev wifi | grep -E '^[*]' | awk '/*/ {print $8}')
        TOTALDOWN=$(ifconfig wlan1| grep "RX packets" | awk {'print $6 $7'})
        TOTALUP=$(ifconfig wlan1| grep "TX packets" | awk {'print $6 $7'})
        xsetroot -name "CPU:$CPU | Mem:$MEM | Net: $NET up: $TOTALUP down: $TOTALDOWN | $LOCALTIME | BAT: $BHT"

        sleep 1s
done &
